In [1]:
# --- [CELL 0]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 1}
import pandas as pd
df = pd.read_csv('data/training.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72983 entries, 0 to 72982
Data columns (total 34 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   RefId                              72983 non-null  int64
 1   IsBadBuy                           72983 non-null  int64
 2   PurchDate                          72983 non-null  object
 3   Auction                            72983 non-null  object
 4   VehYear                            72983 non-null  int64
 5   VehicleAge                         72983 non-null  int64
 6   Make                               72983 non-null  object
 7   Model                              72983 non-null  object
 8   Trim                               70623 non-null  object
 9   SubModel                           72975 non-null  object
 10  Color                              72975 non-null  object
 11  Transmission                       72974 non-null  object
 12  WheelTypeID                        69814 non-null  float64
 13  WheelType                          69809 non-null  object
 14  VehOdo                             72983 non-null  int64
 15  Nationality                        72978 non-null  object
 16  Size                               72978 non-null  object
 17  TopThreeAmericanName               72978 non-null  object
 18  MMRAcquisitionAuctionAveragePrice  72965 non-null  float64
 19  MMRAcquisitionAuctionCleanPrice    72965 non-null  float64
 20  MMRAcquisitionRetailAveragePrice   72965 non-null  float64
 21  MMRAcquisitonRetailCleanPrice      72965 non-null  float64
 22  MMRCurrentAuctionAveragePrice      72668 non-null  float64
 23  MMRCurrentAuctionCleanPrice        72668 non-null  float64
 24  MMRCurrentRetailAveragePrice       72668 non-null  float64
 25  MMRCurrentRetailCleanPrice         72668 non-null  float64
 26  PRIMEUNIT                          3419 non-null   object
 27  AUCGUART                           3419 non-null   object
 28  BYRNO                              72983 non-null  int64
 29  VNZIP1                             72983 non-null  int64
 30  VNST                               72983 non-null  object
 31  VehBCost                           72983 non-null  float64
 32  IsOnlineSale                       72983 non-null  int64
 33  WarrantyCost                       72983 non-null  int64
dtypes: float64(10), int64(9), object(15)
memory usage: 18.9+ MB

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,...,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,...,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,...,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,...,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,...,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,73010,1,12/2/2009,ADESA,2001,8,MERCURY,SABLE,GS,4D SEDAN GS,...,4836.0,5937.0,NaN,NaN,18111,30212,GA,4200.0,0,993
72979,73011,0,12/2/2009,ADESA,2007,2,CHEVROLET,MALIBU 4C,LS,4D SEDAN LS,...,10151.0,11652.0,NaN,NaN,18881,30212,GA,6200.0,0,1038
72980,73012,0,12/2/2009,ADESA,2005,4,JEEP,GRAND CHEROKEE 2WD V,Lar,4D WAGON LAREDO,...,11831.0,14402.0,NaN,NaN,18111,30212,GA,8200.0,0,1893
72981,73013,0,12/2/2009,ADESA,2006,3,CHEVROLET,IMPALA,LS,4D SEDAN LS,...,10099.0,11228.0,NaN,NaN,18881,30212,GA,7000.0,0,1974
72982,73014,0,12/2/2009,ADESA,2006,3,MAZDA,MAZDA6,s,4D SEDAN S,...,11954.0,13246.0,NaN,NaN,18111,30212,GA,8000.0,0,1313

In [2]:
# --- [CELL 1]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 2}
columns_to_remove = ['PurchDate', 'VehYear', 'WheelTypeID', 'BYRNO', 'VNZIP1', 'Model', 'Trim', 'VNST', 'SubModel']
df

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,1,0,12/7/2009,ADESA,2006,3,MAZDA,MAZDA3,i,4D SEDAN I,...,11597.0,12409.0,NaN,NaN,21973,33619,FL,7100.0,0,1113
1,2,0,12/7/2009,ADESA,2004,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,...,11374.0,12791.0,NaN,NaN,19638,33619,FL,7600.0,0,1053
2,3,0,12/7/2009,ADESA,2005,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,...,7146.0,8702.0,NaN,NaN,19638,33619,FL,4900.0,0,1389
3,4,0,12/7/2009,ADESA,2004,5,DODGE,NEON,SXT,4D SEDAN,...,4375.0,5518.0,NaN,NaN,19638,33619,FL,4100.0,0,630
4,5,0,12/7/2009,ADESA,2005,4,FORD,FOCUS,ZX3,2D COUPE ZX3,...,6739.0,7911.0,NaN,NaN,19638,33619,FL,4000.0,0,1020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72978,73010,1,12/2/2009,ADESA,2001,8,MERCURY,SABLE,GS,4D SEDAN GS,...,4836.0,5937.0,NaN,NaN,18111,30212,GA,4200.0,0,993
72979,73011,0,12/2/2009,ADESA,2007,2,CHEVROLET,MALIBU 4C,LS,4D SEDAN LS,...,10151.0,11652.0,NaN,NaN,18881,30212,GA,6200.0,0,1038
72980,73012,0,12/2/2009,ADESA,2005,4,JEEP,GRAND CHEROKEE 2WD V,Lar,4D WAGON LAREDO,...,11831.0,14402.0,NaN,NaN,18111,30212,GA,8200.0,0,1893
72981,73013,0,12/2/2009,ADESA,2006,3,CHEVROLET,IMPALA,LS,4D SEDAN LS,...,10099.0,11228.0,NaN,NaN,18881,30212,GA,7000.0,0,1974
72982,73014,0,12/2/2009,ADESA,2006,3,MAZDA,MAZDA6,s,4D SEDAN S,...,11954.0,13246.0,NaN,NaN,18111,30212,GA,8000.0,0,1313

In [3]:
# --- [CELL 2]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 3}
target = df['IsBadBuy']
inputs = df.drop(columns=['IsBadBuy'])

In [4]:
# --- [CELL 3]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 4}
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(inputs, target, test_size=0.2, random_state=1)
inputs=x_train

In [5]:
# --- [CELL 4]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 5}
column_ranges={
    'VehicleAge': (0,30),
    'VehOdo': (0,120000),
    'MMRAcquisitionAuctionAveragePrice': (800,46000),
    'MMRAcquisitionAuctionCleanPrice': (1000,46000),
    'MMRAcquisitionRetailAveragePrice': (1000,46000),
    'MMRAcquisitonRetailCleanPrice': (1000,46000),
    'MMRCurrentAuctionAveragePrice': (300,46000), 
    'MMRCurrentAuctionCleanPrice': (400,46000), 
    'MMRCurrentRetailAveragePrice': (800,46000),
    'MMRCurrentRetailCleanPrice': (1000,46000),
    'VehBCost': (1000,46000),                         
    'WarrantyCost': (400,8000) 
}
for column, (min_val, max_val) in column_ranges.items():
    out_of_range_count = ((inputs[column] < min_val) | (inputs[column] > max_val)).sum()
    print(f"The number of out-of-range cells in '{column}' variable is: {out_of_range_count}")

for column , (min_val,max_val) in column_ranges.items():
    inputs[column]=inputs[column].apply(lambda x:x if min_val<=x<=max_val else None)
#print(inputs)
inputs.describe()

The number of out-of-range cells in 'VehicleAge' variable is: 0
The number of out-of-range cells in 'VehOdo' variable is: 0
The number of out-of-range cells in 'MMRAcquisitionAuctionAveragePrice' variable is: 653
The number of out-of-range cells in 'MMRAcquisitionAuctionCleanPrice' variable is: 653
The number of out-of-range cells in 'MMRAcquisitionRetailAveragePrice' variable is: 653
The number of out-of-range cells in 'MMRAcquisitonRetailCleanPrice' variable is: 653
The number of out-of-range cells in 'MMRCurrentAuctionAveragePrice' variable is: 378
The number of out-of-range cells in 'MMRCurrentAuctionCleanPrice' variable is: 378
The number of out-of-range cells in 'MMRCurrentRetailAveragePrice' variable is: 378
The number of out-of-range cells in 'MMRCurrentRetailCleanPrice' variable is: 378
The number of out-of-range cells in 'VehBCost' variable is: 1
The number of out-of-range cells in 'WarrantyCost' variable is: 0

,RefId,VehYear,VehicleAge,WheelTypeID,VehOdo,MMRAcquisitionAuctionAveragePrice,MMRAcquisitionAuctionCleanPrice,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,BYRNO,VNZIP1,VehBCost,IsOnlineSale,WarrantyCost
count,58386.000000,58386.000000,58386.000000,55831.000000,58386.000000,57720.000000,57720.000000,57720.000000,57720.000000,57759.000000,57759.000000,57759.000000,57759.000000,58386.000000,58386.000000,58385.000000,58386.000000,58386.000000
mean,36568.705049,2005.344021,4.176755,1.493794,71513.896807,6199.205942,7458.774238,8594.903638,9965.698753,6174.136412,7440.725463,8838.077858,10216.675566,26339.854194,58024.008855,6730.852554,0.025229,1277.312678
std,21053.407634,1.731245,1.714003,0.521156,14564.492293,2391.790172,2625.363206,3039.491687,3235.208672,2393.760770,2628.746694,3013.614704,3212.107677,25707.421605,26122.474982,1774.470612,0.156820,601.288521
min,1.000000,2001.000000,0.000000,0.000000,5368.000000,889.000000,1240.000000,1543.000000,2009.000000,369.000000,494.000000,899.000000,1034.000000,835.000000,2764.000000,1400.000000,0.000000,462.000000
25%,18367.250000,2004.000000,3.000000,1.000000,61845.000000,4338.000000,5477.000000,6362.750000,7568.000000,4311.000000,5466.000000,6589.000000,7843.000000,17212.000000,32124.000000,5435.000000,0.000000,837.000000
50%,36580.000000,2005.000000,4.000000,1.000000,73361.000000,6137.000000,7353.000000,8483.000000,9837.000000,6086.000000,7339.000000,8758.000000,10127.000000,19662.000000,73108.000000,6700.000000,0.000000,1155.000000
75%,54818.750000,2007.000000,5.000000,2.000000,82433.750000,7780.500000,9038.000000,10672.000000,12111.000000,7743.000000,9022.000000,10921.000000,12312.000000,22808.000000,80022.000000,7900.000000,0.000000,1623.000000
max,73014.000000,2009.000000,9.000000,3.000000,115717.000000,35722.000000,36859.000000,39080.000000,41482.000000,35722.000000,36859.000000,39080.000000,41062.000000,99761.000000,99224.000000,45469.000000,1.000000,7498.000000

In [6]:
# --- [CELL 5]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 6}
import numpy as np
def frequency_table(variable):
    unique_elements,counts=np.unique(variable.dropna(),return_counts=True)
    percentage=(counts/len(variable)*100)
    for i , j , k in zip(unique_elements,counts,percentage):
        print(f"{i} :count{j} , percentage: {k:.2f}")
    return
categorical_fields = [
    "Auction",
    "Make",
    "Color",
    "Transmission",
    "WheelType",
    "Nationality",
    "Size",
    "TopThreeAmericanName",
    "PRIMEUNIT",
    "AUCGUART"
]
continuous_fields = [col for col in inputs.columns if col not in categorical_fields]
for col in categorical_fields:
    print(f"Frequency Table for {col}:")
    frequency_table(inputs[col])
    print("-" * 40)

Frequency Table for Auction:
ADESA :count11578 , percentage: 19.83
MANHEIM :count32771 , percentage: 56.13
OTHER :count14037 , percentage: 24.04
----------------------------------------
Frequency Table for Make:
ACURA :count28 , percentage: 0.05
BUICK :count588 , percentage: 1.01
CADILLAC :count19 , percentage: 0.03
CHEVROLET :count13757 , percentage: 23.56
CHRYSLER :count7105 , percentage: 12.17
DODGE :count10267 , percentage: 17.58
FORD :count9086 , percentage: 15.56
GMC :count505 , percentage: 0.86
HONDA :count392 , percentage: 0.67
HUMMER :count1 , percentage: 0.00
HYUNDAI :count1447 , percentage: 2.48
INFINITI :count31 , percentage: 0.05
ISUZU :count115 , percentage: 0.20
JEEP :count1324 , percentage: 2.27
KIA :count1959 , percentage: 3.36
LEXUS :count29 , percentage: 0.05
LINCOLN :count81 , percentage: 0.14
MAZDA :count776 , percentage: 1.33
MERCURY :count736 , percentage: 1.26
MINI :count18 , percentage: 0.03
MITSUBISHI :count812 , percentage: 1.39
NISSAN :count1666 , percentage: 2.85
OLDSMOBILE :count198 , percentage: 0.34
PLYMOUTH :count2 , percentage: 0.00
PONTIAC :count3454 , percentage: 5.92
SATURN :count1732 , percentage: 2.97
SCION :count97 , percentage: 0.17
SUBARU :count25 , percentage: 0.04
SUZUKI :count1071 , percentage: 1.83
TOYOTA :count926 , percentage: 1.59
TOYOTA SCION :count1 , percentage: 0.00
VOLKSWAGEN :count108 , percentage: 0.18
VOLVO :count30 , percentage: 0.05
----------------------------------------
Frequency Table for Color:
BEIGE :count1265 , percentage: 2.17
BLACK :count6115 , percentage: 10.47
BLUE :count8276 , percentage: 14.17
BROWN :count357 , percentage: 0.61
GOLD :count4176 , percentage: 7.15
GREEN :count2546 , percentage: 4.36
GREY :count6313 , percentage: 10.81
MAROON :count1673 , percentage: 2.87
NOT AVAIL :count79 , percentage: 0.14
ORANGE :count328 , percentage: 0.56
OTHER :count192 , percentage: 0.33
PURPLE :count310 , percentage: 0.53
RED :count5012 , percentage: 8.58
SILVER :count11841 , percentage: 20.28
WHITE :count9697 , percentage: 16.61
YELLOW :count198 , percentage: 0.34
----------------------------------------
Frequency Table for Transmission:
AUTO :count56297 , percentage: 96.42
MANUAL :count2079 , percentage: 3.56
Manual :count1 , percentage: 0.00
----------------------------------------
Frequency Table for WheelType:
Alloy :count28851 , percentage: 49.41
Covers :count26376 , percentage: 45.18
Special :count599 , percentage: 1.03
----------------------------------------
Frequency Table for Nationality:
AMERICAN :count48852 , percentage: 83.67
OTHER :count156 , percentage: 0.27
OTHER ASIAN :count6394 , percentage: 10.95
TOP LINE ASIAN :count2980 , percentage: 5.10
----------------------------------------
Frequency Table for Size:
COMPACT :count5745 , percentage: 9.84
CROSSOVER :count1369 , percentage: 2.34
LARGE :count7071 , percentage: 12.11
LARGE SUV :count1167 , percentage: 2.00
LARGE TRUCK :count2501 , percentage: 4.28
MEDIUM :count24645 , percentage: 42.21
MEDIUM SUV :count6478 , percentage: 11.10
SMALL SUV :count1824 , percentage: 3.12
SMALL TRUCK :count693 , percentage: 1.19
SPECIALTY :count1515 , percentage: 2.59
SPORTS :count631 , percentage: 1.08
VAN :count4743 , percentage: 8.12
----------------------------------------
Frequency Table for TopThreeAmericanName:
CHRYSLER :count18695 , percentage: 32.02
FORD :count9903 , percentage: 16.96
GM :count20254 , percentage: 34.69
OTHER :count9530 , percentage: 16.32
----------------------------------------
Frequency Table for PRIMEUNIT:
NO :count2691 , percentage: 4.61
YES :count46 , percentage: 0.08
----------------------------------------
Frequency Table for AUCGUART:
GREEN :count2674 , percentage: 4.58
RED :count63 , percentage: 0.11
----------------------------------------

In [7]:
# --- [CELL 6]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 7}
inputs["Transmission"]=inputs["Transmission"].replace("Manual",'MANUAL')
frequency_table(inputs["Transmission"])
print("-"*40)
inputs["Color"].info()
print("-"*40)
inputs["Color"]=inputs["Color"].replace("NOT AVAIL",np.nan)
inputs["Color"].info()

AUTO :count56297 , percentage: 96.42
MANUAL :count2080 , percentage: 3.56
----------------------------------------
<class 'pandas.core.series.Series'>
Index: 58386 entries, 63148 to 5192
Series name: Color
Non-Null Count  Dtype
--------------  -----
58378 non-null  object
dtypes: object(1)
memory usage: 912.3+ KB
----------------------------------------
<class 'pandas.core.series.Series'>
Index: 58386 entries, 63148 to 5192
Series name: Color
Non-Null Count  Dtype
--------------  -----
58299 non-null  object
dtypes: object(1)
memory usage: 912.3+ KB

In [8]:
# --- [CELL 7]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 8}
def replace_rare_classes(df, column, threshold=1):
    unique_elements, counts = np.unique(df[column].dropna(), return_counts=True)
    percentage = (counts / len(df[column])) * 100
    rare_classes = [elem for elem, pct in zip(unique_elements, percentage) if pct < threshold]
    return df[column].replace(rare_classes, 'OTHER')

inputs['Make'] = replace_rare_classes(inputs, 'Make', threshold=1)
print("\nUpdated Frequency Table for 'Make':")
frequency_table(inputs['Make'])


inputs['Color'] = replace_rare_classes(inputs, 'Color', threshold=1)
print("\nUpdated Frequency Table for 'Color':")
frequency_table(inputs['Color'])

Updated Frequency Table for 'Make':
BUICK :count588 , percentage: 1.01
CHEVROLET :count13757 , percentage: 23.56
CHRYSLER :count7105 , percentage: 12.17
DODGE :count10267 , percentage: 17.58
FORD :count9086 , percentage: 15.56
HYUNDAI :count1447 , percentage: 2.48
JEEP :count1324 , percentage: 2.27
KIA :count1959 , percentage: 3.36
MAZDA :count776 , percentage: 1.33
MERCURY :count736 , percentage: 1.26
MITSUBISHI :count812 , percentage: 1.39
NISSAN :count1666 , percentage: 2.85
OTHER :count1680 , percentage: 2.88
PONTIAC :count3454 , percentage: 5.92
SATURN :count1732 , percentage: 2.97
SUZUKI :count1071 , percentage: 1.83
TOYOTA :count926 , percentage: 1.59

Updated Frequency Table for 'Color':
BEIGE :count1265 , percentage: 2.17
BLACK :count6115 , percentage: 10.47
BLUE :count8276 , percentage: 14.17
GOLD :count4176 , percentage: 7.15
GREEN :count2546 , percentage: 4.36
GREY :count6313 , percentage: 10.81
MAROON :count1673 , percentage: 2.87
OTHER :count1385 , percentage: 2.37
RED :count5012 , percentage: 8.58
SILVER :count11841 , percentage: 20.28
WHITE :count9697 , percentage: 16.61

In [9]:
# --- [CELL 8]: ---
# cell_state: edited
# execution_status: {'status': 'error', 'done': True, 'execution_count': 9}
# === BEFORE (original) ===
# print(f"Number of continuous fields before feature screening: {len(continuous_fields)}")
# print(f"Number of categorical fields before feature screening: {len(categorical_fields)}")
# 
# min_cv=0.1
# cv_values=inputs[continuous_fields].std()/inputs[continuous_fields].mean()
# selected_columns=cv_values[cv_values<0.1].index
# print(f"\nNumber of Features with a coefficient of variation less than **0.1**: {len(selected_columns)}")
# filtered_con=inputs[selected_columns]
# inputs_con=inputs[continuous_fields].drop(selected_columns,axis=1)
# 
# threshold=99
# mode_category=(inputs[categorical_fields].apply(lambda x:x.value_counts().max()/len(x)*100))
# selected_categorical_columns=mode_category[mode_category>threshold].index
# print(f"Number of features where the mode category percentage is greater than **99%**: {len(selected_columns)}")
# mode_filtered_inputs=inputs[selected_categorical_columns]
# inputs_cat=inputs[categorical_fields].drop(selected_categorical_columns,axis=1)
# 
# threshold=90
# distinct_percentage=inputs_cat[categorical_fields].apply(lambda x:x.dropna().nunique()/x.count()*100)
# selected_categorical_columns=distinct_percentage[distinct_percentage>threshold].index
# print(f"Number of Features with a percentage of unique categories exceeding **90%**: {len(selected_columns)}")
# distinct_filtered_inputs=inputs_cat[selected_categorical_columns]
# inputs_cat=inputs[categorical_fields].drop(selected_categorical_columns,axis=1)
# 
# filtered_df=pd.concat([inputs_con,inputs_cat,target],axis=1)
# 
# print(f"\nNumber of continuous fields AFTER feature screening: {len(continuous_fields)}")
# print(f"Number of categorical fields AFTER feature screening: {len(categorical_fields)}")

# === AFTER (edited) ===
print(f"Number of continuous fields before feature screening: {len(continuous_fields)}")
print(f"Number of categorical fields before feature screening: {len(categorical_fields)}")

min_cv=0.1
cv_values=inputs[continuous_fields].std()/inputs[continuous_fields].mean()
selected_columns=cv_values[cv_values<0.1].index
print(f"\nNumber of Features with a coefficient of variation less than **0.1**: {len(selected_columns)}")
filtered_con=inputs[selected_columns]
inputs_con=inputs[continuous_fields].drop(selected_columns,axis=1)

threshold=99
mode_category=(inputs[categorical_fields].apply(lambda x:x.value_counts().max()/len(x)*100))
selected_categorical_columns=mode_category[mode_category>threshold].index
print(f"Number of features where the mode category percentage is greater than **99%**: {len(selected_categorical_columns)}")
mode_filtered_inputs=inputs[selected_categorical_columns]
inputs_cat=inputs[categorical_fields].drop(selected_categorical_columns,axis=1)
categorical_fields = [col for col in categorical_fields if col not in selected_categorical_columns]

threshold=90
distinct_percentage=inputs_cat[categorical_fields].apply(lambda x:x.dropna().nunique()/x.count()*100)
selected_categorical_columns=distinct_percentage[distinct_percentage>threshold].index
print(f"Number of Features with a percentage of unique categories exceeding **90%**: {len(selected_categorical_columns)}")
distinct_filtered_inputs=inputs_cat[selected_categorical_columns]
inputs_cat=inputs_cat.drop(selected_categorical_columns,axis=1)
categorical_fields = [col for col in categorical_fields if col not in selected_categorical_columns]

filtered_df=pd.concat([inputs_con,inputs_cat,target],axis=1)

print(f"\nNumber of continuous fields AFTER feature screening: {len(inputs_con.columns)}")
print(f"Number of categorical fields AFTER feature screening: {len(inputs_cat.columns)}")

Number of continuous fields before feature screening: 23
Number of categorical fields before feature screening: 10

TypeError: could not convert string to float: '10/18/2010'

In [10]:
import numpy as np
import pandas as pd

assert 'continuous_fields' in globals(), "continuous_fields should exist"
assert 'inputs' in globals(), "inputs should exist"
assert 'filtered_df' in globals(), "filtered_df should be created"

expected_continuous = [
    col for col in inputs.columns
    if col not in categorical_fields and pd.api.types.is_numeric_dtype(inputs[col])
]

assert set(continuous_fields) == set(expected_continuous), (
    f"continuous_fields mismatch: {set(continuous_fields)} vs {set(expected_continuous)}"
)
assert 'PurchDate' not in continuous_fields, "PurchDate should not be treated as continuous"
assert np.isfinite(inputs[continuous_fields].to_numpy(dtype=float, copy=False)).any(), (
    "continuous_fields should contain valid numeric values"
)
assert filtered_df.shape[1] > 0, "filtered_df should not be empty"
assert filtered_df['IsBadBuy'].notna().all(), "target column should remain valid"

AssertionError: filtered_df should be created